/**
 * Created by brooks on 9/14/2021.
 */

@IsTest
private class OpportunityUpdater_Tests {
    @IsTest
    static void itShouldUpdateOpportunities() {

       /* List<Opportunity> opportunities = [
                SELECT Id, Description
                FROM Opportunity
                LIMIT 2
        ];

        Opportunity firstOpp = opportunities[0];
        Opportunity secondOpp = opportunities[1];

        List<OpportunityLineItem> lineItems = new List<OpportunityLineItem>{
                new OpportunityLineItem(OpportunityId = firstOpp.Id,
                        Description = 'Business Logic stuff')
        };

        OpportunityLineItemRepoMock mock = new OpportunityLineItemRepoMock();
        mock.lineItems = lineItems;*/


    }
}