/**
 * Created by brooks on 9/14/2021.
 */

@IsTest
private class Repository_Tests {
    @IsTest
    static void itShouldTakeInAQuery() {
        /*Query basicQuery = new Query(Opportunity.IsWon, Query.Operator.Equals, true);
        IRepository repo = new Repository(
                Opportunity.SObjectType, new List<SObjectField>{Opportunity.Id}
        );

        repo.get(basicQuery);
        System.assertEquals(1, Limits.getQueries());*/
    }
}